name: yoursportz
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  video_player: ^2.8.3
  lottie: ^3.1.0
  aad_oauth: ^1.0.1
  flutter_reaction_button: ^3.0.0+3
  shared_preferences: ^2.2.2
  animated_splash_screen: ^1.3.0
  http: ^1.2.1
  intl: ^0.19.0
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.2.0
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.2.1
  flutter_animation_progress_bar: ^2.3.1
  otpless_flutter: ^2.1.3
  carousel_slider: ^4.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  share_plus: ^7.2.2
  socket_io_client: ^2.0.3+1
  geolocator: ^12.0.0
  easy_localization: ^3.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf